name: Linter

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install pycodestyle
          pip install pylint
          pip install pylint_runner

      - name: pycodestyle
        run: |
          pycodestyle --version
          pycodestyle . --ignore=E402,E501,W503,W504

      - name: pylint
        run: |
          python -m pylint --version
          pylint_runner --version
          pylint_runner
